#!/bin/sh
#
# test that the output of a test matches the #^ prefixed lines in the test file.
#
E=expected.tmp
A=actual.tmp
function run() {
   echo $1
   sed -n '/#\^ /s/#\^ //p' $1 > $E
   ../memory $1 > $A
   diff -u --strip-trailing-cr $E $A
}

if [ $# != 0 ]
then
        run $1
else
        for i in *.scr
        do
            run $i
        done
fi

rm -f $E $A
